<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthday_birthday</name>
   <tag></tag>
   <elementGuidId>c1e6931a-71cc-478e-a8d8-cc20f5300d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthday']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#birthday</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32f0474f-f191-4907-b6eb-41c27c76835f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48a5b1b7-569a-4207-a870-ecae398bdd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bf5c62eb-1da6-40cc-a324-4ad0cce09462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>dc420983-cb98-4aaa-89e2-ce21dea07dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2001/07/02</value>
      <webElementGuid>77a7e16c-f303-4d5e-b33d-b8787a377e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy/mm/dd</value>
      <webElementGuid>d1158ad6-3bc6-494d-a432-811bbf7ff5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>eeed483a-5d49-46be-84d0-3f47dc29167b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>(?:19|20)[0-9]{2}[/.](?:(?:0[1-9]|1[0-2])[/.](?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))</value>
      <webElementGuid>67c2997d-fcfa-4ff2-9fe6-05e92a759c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthday&quot;)</value>
      <webElementGuid>f9fd186d-546d-427c-a121-5541db71f291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthday']</value>
      <webElementGuid>d49ff50a-4222-4b0c-906a-f4eb7831e86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>3ce1eece-6b85-4312-aa97-7ec1f40e61d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'birthday' and @placeholder = 'yyyy/mm/dd' and @id = 'birthday']</value>
      <webElementGuid>357ef705-c6ff-4594-b18a-00a0ec4c37a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
