<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Post name_postName</name>
   <tag></tag>
   <elementGuidId>cd0f71ef-a28a-45c2-aa1a-60c86c935207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0204edc7-8653-4bf8-af54-4a3a4dc35064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e0b7882-6fe5-4eaa-9dd1-198f1964cfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ed6a4565-556b-47fd-937d-556ad8f5bb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postName</value>
      <webElementGuid>f6c2467a-55ff-4645-b5ca-971cf21f27cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postName</value>
      <webElementGuid>36cf1ba8-eaf0-4fff-bb6f-f3591cb72c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Post Name...</value>
      <webElementGuid>5d6e9f41-7770-4f14-8578-229ebc2570c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postName&quot;)</value>
      <webElementGuid>43db721d-2066-41b4-8e1b-0dbcefcac1df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postName']</value>
      <webElementGuid>5e8fa098-497b-4b22-812f-b5f60da259cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f71dc56a-2bdc-43ad-b548-18c34fee4a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'postName' and @id = 'postName' and @placeholder = 'Enter Post Name...']</value>
      <webElementGuid>34577343-ff45-4f66-ab5d-6c6cccc0ca87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
