<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Post Text_postText</name>
   <tag></tag>
   <elementGuidId>a0d08529-66a1-494a-bf4a-f2fe2482e97d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='postText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b3d6d0b1-c4ea-471c-8bb0-a62e7d54b1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postText</value>
      <webElementGuid>291aa71c-2f49-4a0a-af1a-5bb257a3c1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postText</value>
      <webElementGuid>62f41224-a24e-4ce5-b621-8a35e0397080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6f6dbafa-036d-4026-820e-bac0760b737b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>8dab867e-760f-4efd-a7e4-f283098935c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e1c192de-2624-46b3-9e56-5ee1e5bef27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>9f8ac2d2-d7bd-44bc-84c7-15fddae95991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Post Text...</value>
      <webElementGuid>8916d0ae-5e5a-4a5b-b4f5-e84500e984aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postText&quot;)</value>
      <webElementGuid>250c5119-1faf-4787-bd5e-991e8bad245b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='postText']</value>
      <webElementGuid>b5e39105-1fc7-4937-bdb6-732acd244838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2fb72c72-eee0-4d40-bce5-0286075fe57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'postText' and @id = 'postText' and @placeholder = 'Enter Post Text...']</value>
      <webElementGuid>af99fad8-0bd9-4a2a-88fb-2af1ac07688b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
