<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Registration</name>
   <tag></tag>
   <elementGuidId>beea018a-e892-4345-af5c-ae63e36ec6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='registration-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>915425ea-4200-4f48-bd0f-b5635765ccab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-link</value>
      <webElementGuid>bb711069-4bc5-4a70-a371-84fd473c09e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/simple-blog/redirect/registration;jsessionid=0SAHbFgQpgS9mu_PQTKvECVmJyGGRv3gV_dzapWQlefWsDvFBnZy!-402322966</value>
      <webElementGuid>81a04879-cec3-404e-88f2-0501489516cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registration</value>
      <webElementGuid>62dd8d9d-100f-4ab2-b8e5-a32101203f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-link&quot;)</value>
      <webElementGuid>85cb38ea-23bb-4753-bd16-cc5ec8f43280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='registration-link']</value>
      <webElementGuid>4162a8cc-6f1e-4850-8a3f-681a664e446f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Registration')]</value>
      <webElementGuid>4e308d22-353f-476f-b750-b54c8f7f433d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>81c7a3d8-168b-47b9-af39-43ce188195fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::a[1]</value>
      <webElementGuid>1f198e26-a78e-4295-9d93-8916c12d7371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'registration-link', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>831e04bc-a975-40c4-9aa7-4aee341a0894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/simple-blog/redirect/registration;jsessionid=0SAHbFgQpgS9mu_PQTKvECVmJyGGRv3gV_dzapWQlefWsDvFBnZy!-402322966')])[2]</value>
      <webElementGuid>661dfb66-3fa7-43df-abfe-29b0651b2f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>d2c4205d-5d01-41bf-ba72-a262d2b3e906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'registration-link' and @href = '/simple-blog/redirect/registration;jsessionid=0SAHbFgQpgS9mu_PQTKvECVmJyGGRv3gV_dzapWQlefWsDvFBnZy!-402322966' and (text() = 'Registration' or . = 'Registration')]</value>
      <webElementGuid>410877ed-c22f-4d45-977e-f0fef04a5195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/simple-blog/redirect/registration;jsessionid=BooHaJfRgmhS-pSb0zyubCIbHfjIcD93IF1nq1pbj567vjaLSHGB!-402322966')])[2]</value>
      <webElementGuid>60e5ef57-0fd8-4c96-b80f-a054a169112a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'registration-link' and @href = '/simple-blog/redirect/registration;jsessionid=BooHaJfRgmhS-pSb0zyubCIbHfjIcD93IF1nq1pbj567vjaLSHGB!-402322966' and (text() = 'Registration' or . = 'Registration')]</value>
      <webElementGuid>126b72fe-9743-4c34-856e-3d66042045f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
